### PR TITLE
Use persistence traits

### PR DESCRIPTION
**Pull request by pine3ree**
Use new persistence traits, remove local redundant methods in favor of trait methods

### CODE REVIEW

**Comment by pine3ree** [comment]
Note:
- as for mezzio-session-ext I had to change the minimum stability in order to use mezzio-session 1.4.x branch

**Comment by weierophinney** [comment]
> * as for mezzio-session-ext I had to change the minimum stability in order to use mezzio-session 1.4.x branch

1.4.0 is now released. :)

**Comment by pine3ree** [comment]
> > * as for mezzio-session-ext I had to change the minimum stability in order to use mezzio-session 1.4.x branch
> 
> 1.4.0 is now released. :)

Oh...I fetched the upstream just before updating the PR, but composer complained. Maybe the local packagist distribution node was not in sync yet. I'll check tomorrow again locally and rever the minimum stability requirements (...for mezzio-session-ext as well :) )

kind regards

**Comment by pine3ree** [comment]
There is an failing unrelated test: https://travis-ci.com/github/mezzio/mezzio-session-cache/jobs/396614500#L367
The failure message reads:

Cookie expiry "Wed, 07 Oct 2020 22:47:00 +0000" is not at least "Wed, 07 Oct 2020 22:46:59 +0000" 

which is itself suggesting that there is something wrong. 

The same code passed all the tests both locally and in my travis account (https://travis-ci.org/github/pine3ree/mezzio-session-cache/builds/733817493), and I believe it has to do with "microtime" differences.

I'll look into that.

**Comment by weierophinney** [comment]
Don't worry about it, @pine3ree — this is definitely a case of microtime issues (look at the last ms - 59 -> 00), and it only occurred in one env. I'm going to go ahead and merge.

**Comment by pine3ree** [comment]
> Don't worry about it, @pine3ree — this is definitely a case of microtime issues (look at the last ms - 59 -> 00), and it only occurred in one env. I'm going to go ahead and merge.

OK, but I will look into that in the next days. I experienced similar failures in the past. In mezzio-session-ext/persistence-traits I used a min expected value and a max expected value for comparison in the end. Even if rare, a test failure is always annoying: the first thing you think is that your most recent changes caused the error, so it's better to be sure it's not (or that it is).

kind regards

**Pull request merged**
